### ISSUE TITLE
您好,请问蓝牙无法正常使用,搜索不到设备一般是什么问题呢

### ISSUE THREAD

**Issue by 496128237** [badfellow/Hackintosh_M4800#1]
您好,请问蓝牙无法正常使用,搜索不到设备一般是什么问题呢

**Comment by hansyao** [comment]
可能是驱动问题，你蓝牙是什么型号的？如果和我的蓝牙型号一样的4352， 可替换为我精简过的驱动试试看https://github.com/hansyao/BrcmPatchRAM
