### ISSUE TITLE
Bigsur 11.4 hang at boot

### ISSUE THREAD

**Issue by ds2k5** [badfellow/Hackintosh_M4800#2]
Hi,
most times the system hang at boot with BigSur 11.4.
Som times it boots.
How to see what is wrong ?

**Comment by hansyao** [comment]
first of all, please check your hardware list whether it's fully same as mine. https://github.com/badfellow/Hackintosh_M4800/tree/master/OpenCore

if  yes, you may double check the PCI list whether hardware address is same.

if not, please check the log what stuck the boot (mostly it's hardware driver compatibility issue)and then you would be able to find the way to fix the issues.

**Comment by ds2k5** [comment]
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I217-LM (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d4)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d4)
00:1c.3 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 (rev d4)
00:1c.4 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #5 (rev d4)
00:1c.6 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #7 (rev d4)
00:1c.7 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #8 (rev d4)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation QM87 Express LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK106GLM [Quadro K2100M] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK106 HDMI Audio Controller (rev a1)
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 73)
11:00.0 SD Host controller: O2 Micro, Inc. SD/MMC Card Reader Controller (rev 01)

**Comment by hansyao** [comment]
Pay attention to your wifi adapter and GPU which not same as mine.
```s
01:00.0 VGA compatible controller: NVIDIA Corporation GK106GLM [Quadro K2100M] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK106 HDMI Audio Controller (rev a1)
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 73)
```
The key is that your WIFI adapter is intel 7260. you must remove below 4 kexts from my EFI package and replace to appropriate Intel driver. In the meanwhile, you need to remove [line 1379-1408](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L1379-L1408)  in dsl file [SSDT-Dell-M4800.dsl](../blob/master/OpenCore/SSDT-Dell-M4800.dsl), and then recompile to replace [SSDT-Dell-M4800.aml](../blob/master/OpenCore/EFI/OC/ACPI/SSDT-Dell-M4800.aml).
```s
AirportBrcmFixup.kext
BrcmBluetoothInjector.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext
```
For other kexts, you could use my kexts in EFI package but please **DO NOT** upgrade to officials because some of my kexts have some modifications to adapt ACPI structure.

**Comment by ds2k5** [comment]
Thanks a lot! Not it works fine!

iasl SSDT-Dell-M4800.dsl 
cp /mnt/EFI/OC/ACPI/SSDT-Dell-M4800.aml

cp airportitlwm.kext to  /mnt/EFI/OC/kexts
with Clover Configurator: add the airportitlwm.kext v1.3 to kexts
