### ISSUE TITLE
Small problem with install opencore

### ISSUE THREAD

**Issue by adiif1** [badfellow/Hackintosh_M4800#3]
Hello, I ask you I use files from

 The 1st stage of the installation is great (the entire disk is dedicated to osx), the difference between my model is the CPU I have 4910MQ And k2100M during the second stage of installation, i.e. restart, the installation is on 20% of the bar and so it stands

 The pendrive stops flashing just like the SSD, should I remove something during the installation?  To change?

**Comment by hansyao** [comment]
see also [#2](../issues/2#issuecomment-877923827), you could firstly check your full [PCI LIST](../tree/master/OpenCore/SSDT-Dell-M4800.dsl#L14-L53) whether is same as mine and then check the verbose log to see what cause the issues and find the solutions. Be sure the vendor-id and device-id need to be same as well if you'd like to apply my EFI with 100% workable.

by the way, the CPU 4910MQ and GPU K2100M you mentioned would not be the issue as it's compatible with ACPI spec with mine.

**Comment by adiif1** [comment]
Thanx for help :)
that is my api 

https://pastebin.com/rAdLDAg9

can u help me with my bluetooth? I change wifi card to BCM94360CS2 I remove 4 kext and  line 1379-1408 in dsl file SSDT-Dell-M4800.dsl, and then recompile to replace SSDT-Dell-M4800.aml.


Could you reveal which kext were edited by you so as not to touch them?

( Be sure the vendor-id and device-id need to be same as well if you'd like to apply my EFI with 100% workable.) how to change in GPU?

**Comment by hansyao** [comment]
> Thanx for help :)
> that is my api
> 
> https://pastebin.com/rAdLDAg9
> 
> can u help me with my bluetooth? I change wifi card to BCM94360CS2 I remove 4 kext and line 1379-1408 in dsl file SSDT-Dell-M4800.dsl, and then recompile to replace SSDT-Dell-M4800.aml.
> 
> Could you reveal which kext were edited by you so as not to touch them?
> 
> ( Be sure the vendor-id and device-id need to be same as well if you'd like to apply my EFI with 100% workable.) how to change in GPU?

First of all, you need to remove the 4 kexts. and not sure your bluetooth can be fully compatibility within mac built-in driver. but according to your PCI LIST, you should change Scope (_SB.PCI0.**RP03**) to Scope (_SB.PCI0.**RP01**) in [line 1379](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L1380). and replace with your own card description  [line 1397](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L1397). 

Luckily it might work without the kexts. if not you can simply put the 4 kexts from [acidanthera's Repo](https://github.com/acidanthera/BrcmPatchRAM) (pay attention the load sequence in OpenCore). That should 100% work well. 

ps. Optionally, you can remove [line 1379-1408](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L1379-L1408) in DSL file and recompile if you are using [acidanthera's Repo](https://github.com/acidanthera/BrcmPatchRAM) (pay attention the load sequence in OpenCore).

As [my Bluetooth kexts](https://github.com/hansyao/BrcmPatchRAM) is only designed for Dell DW1550 4352+20702 combo, of course not be compatibility with other hardware. 

GPU should not be a problem if you are not intend to change your card rather than external NVIDIA card.

**Comment by adiif1** [comment]
> > Thanx for help :)
> > that is my api
> > https://pastebin.com/rAdLDAg9
> > can u help me with my bluetooth? I change wifi card to BCM94360CS2 I remove 4 kext and line 1379-1408 in dsl file SSDT-Dell-M4800.dsl, and then recompile to replace SSDT-Dell-M4800.aml.
> > Could you reveal which kext were edited by you so as not to touch them?
> > ( Be sure the vendor-id and device-id need to be same as well if you'd like to apply my EFI with 100% workable.) how to change in GPU?
> 
> First of all, you need to remove the 4 kexts. and not sure your bluetooth can be fully compatibility within mac built-in driver. but according to your PCI LIST, you should change Scope (_SB.PCI0.**RP03**) to Scope (_SB.PCI0.**RP01**) in [line 1379](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L1380). and replace with your own card description [line 1397](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L1397).
> 
> Luckily it might work without the kexts. if not you can simply put the 4 kexts from [acidanthera's Repo](https://github.com/acidanthera/BrcmPatchRAM) (pay attention the load sequence in OpenCore). That should 100% work well.
> 
> ps. Optionally, you can remove [line 1379-1408](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L1379-L1408) in DSL file and recompile if you are using [acidanthera's Repo](https://github.com/acidanthera/BrcmPatchRAM) (pay attention the load sequence in OpenCore).
> 
> As [my Bluetooth kexts](https://github.com/hansyao/BrcmPatchRAM) is only designed for Dell DW1550 4352+20702 combo, of course not be compatibility with other hardware.
> 
> GPU should not be a problem if you are not intend to change your card rather than external NVIDIA card.

if I change USBMap.kext to USBInjectAll.kext ( bluetooth has ben work <3 
how to fix them in USBMap? 
this bluetooth use usb

"you should change Scope (_SB.PCI0.RP03) to Scope (_SB.PCI0.RP01) in line 1379. and replace with your own card description line 1397. - no work, only if I install USBInjecyALL"

THANX!

> GPU should not be a problem if you are not intend to change your card rather than external NVIDIA card.

if I want to do it, what then?

**Comment by hansyao** [comment]
Well done. It seams that you've already fixed the Bluetooth driver issue. For usb issue, it's that your device tree is not same is mine. You may check with the tool **IORegistryExplorer** and follow the [dotania guide](https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html#usb-mapping-the-manual-way) to fix it.

For GPU change, you may look into dsl file with the external GPU section and injection with your own parameter. It's a little bit complicated to explain in few words however you should be able to figure it out for unnative-support GPU if you carefully read the guide in GPU section in [dotania guide](https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#native-amd-gpus)

**Comment by adiif1** [comment]
If i change wifi card to AW-CE123H
would everything work?
will there be any kext update?
this is possible to fix this bug in touchpad?

**Comment by hansyao** [comment]
> If i change wifi card to AW-CE123H
> 
> would everything work?
> 
> will there be any kext update?

Not sure. But you may check the supported hardware list in developer's repo
[BrcmPatchRM](https://github.com/acidanthera/BrcmPatchRAM)
