### ISSUE TITLE
大哥好， 想问一下亮度调不到是什么问题呢？ 

### ISSUE THREAD

**Issue by Anonymous341** [badfellow/Hackintosh_M4800#4]
我装了系统后， 就OC升级去0.7.2， 顺带改plist里的序列号， MAC address 等等来启用iServices。 用的序列号也是MBP11,3 的， 但是偏偏调不到亮度， 看得我都快瞎了。其它OC配置跟你的一摸一样。 除了这个问题以外， 一切都正常。 请老哥你帮我想想办法，多谢您了。

配置跟你的大致相同，除了SSD， 电脑换了个1080P的屏幕。之前是 1366x768的， 主板也是LA-9772P。

再次感谢你啊老哥！

**Comment by hansyao** [comment]
亮度问题参见dsl源码 [line 914-985](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L914-L985)部分，按照硬件配置改成你自己的，特别是屏幕edid参数不匹配必改。

**Comment by Anonymous341** [comment]
> 亮度问题参见dsl源码 [line 914-985](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L914-L985)部分，按照硬件配置改成你自己的，特别是屏幕edid参数不匹配必改。

我找到我屏幕的EDID了， 但是要怎么改进DSL 呢？ 比你原来的EDID 长些

**Comment by hansyao** [comment]
另外EDID有问题一定还得修改水平同步宽度，显示器是100就改成32，是32就改成100，具体可参见网上的教程搜索一下一大堆的
![image](https://user-images.githubusercontent.com/6515810/132982416-41d7810d-d838-4b71-b1fb-8fe295254004.jpeg)

**Comment by Anonymous341** [comment]
刚才找的是IOReg 的EDID， 醉了。 现在从win 系统找到屏幕的EDID了， 同步宽度是32， 我先试一试。 请问product ID 需要换成9C7C吗？ 网上有些教程说是需要换的

**Comment by hansyao** [comment]
> 刚才找的是IOReg 的EDID， 醉了。 现在从win 系统找到屏幕的EDID了， 同步宽度是32， 我先试一试。 请问product ID 需要换成9C7C吗？ 网上有些教程说是需要换的

屏幕productid的不需要更改，都包含在edid里了

**Comment by Anonymous341** [comment]
> > 刚才找的是IOReg 的EDID， 醉了。 现在从win 系统找到屏幕的EDID了， 同步宽度是32， 我先试一试。 请问product ID 需要换成9C7C吗？ 网上有些教程说是需要换的
> 
> 屏幕productid的不需要更改，都包含在edid里了

现在SSDT改好了， 同步宽度换成100也不花屏了。 但是偏偏还是调不了亮度。 可以帮我看下吗？ 真的是无策了

![Screen Shot 2021-09-12 at 7 01 00 PM](https://user-images.githubusercontent.com/37086776/132985005-15a7226c-5533-4b97-8a26-a813289110f3.png)

SSDT 和我的 EDID
[https://tmpfiles.org/dl/111946/archive.zip](url)

**Comment by hansyao** [comment]
每台机器硬件配置不一样，需要配合测试，只看这个ssdt没意义。不过花屏解决了你的edid应该是没有问题了，如果硬件一致所有kexts确保用我的包里不要做任何替换和升级，然后你开机清除下NVRAM再关机重启电脑看看

**Comment by Anonymous341** [comment]
> 每台机器硬件配置不一样，需要配合测试，只看这个ssdt没意义。不过花屏解决了你的edid应该是没有问题了，如果硬件一致所有kexts确保用我的包里不要做任何替换和升级，然后你开机清除下NVRAM再关机重启电脑看看

刚刚我试了下， 只换了config.plist 序列号那些， 加个换了EDID 的SSDT， 仍然不行。现在我用会0.7.2， 从你的SSDT里去了PLNF， 再加OC 给的 SSDT-PLNF， 背光反而会比较暗些。但是就是怎么瞎折腾， 也是搞不出调亮度的。醉了真的是醉了😵‍💫。 会是我屏幕的问题吗？不是戴尔原厂的， Windows 和 Linux 可以正常调整。 虽说Linux 我只用独显。

**Comment by hansyao** [comment]
PLNF这个补丁我整合进来了，你再剥离出来用那个独立补丁没意义的，开机后亮度大小是初始化问题，和这个补丁没关系。亮度调节是显卡驱动的问题，有可能有些山寨屏和显卡不兼容，不过这种可能性很小，windows和Linux都没问题的话mac上驱动配置好后肯定也是没问题的

**Comment by Anonymous341** [comment]
> PLNF这个补丁我整合进来了，你再剥离出来用那个独立补丁没意义的，开机后亮度大小是初始化问题，和这个补丁没关系。亮度调节是显卡驱动的问题，有可能有些山寨屏和显卡不兼容，不过这种可能性很小，windows和Linux都没问题的话mac上驱动配置好后肯定也是没问题的

那么请问我升级去0.7.2 会照成这样的问题吗？ 我搜了好久， 就看见驱动是WhateverGreen 和 Lilu 吧。 那么照理来说应该是换对EDID 就行了？ 据我所知， CPU， 主板都是一样的。除非那个亮度驱动跑不了吧？

**Comment by hansyao** [comment]
EDID主要是显示器的色彩和控制，亮度控制是由显卡来驱动显示器的，edid没问题了亮度问题是显卡驱动和主板bios的ACPI规范适配引起的。oc版本有可能有关系，不过可能性很小。

**Comment by hansyao** [comment]
> EDID主要是显示器的色彩和控制，亮度控制是由显卡来驱动显示器的，edid没问题了亮度问题是显卡驱动和主板bios的ACPI规范适配引起的。oc版本有可能有关系，不过可能性很小。

ssdt亮度补丁的逻辑就是修改了acpi规范以适配显示驱动

**Comment by hansyao** [comment]
你得先确认下你的显卡是否完美驱动，如果没有，需要按需更改 [line 914-985](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L928-L936)部分的参数，亮度调节必须显卡完美驱动后才能生效的

**Comment by Anonymous341** [comment]
这样算是兼容吗？ 还是还得改 ig-platform-id？我看 line 937-985 也不需动了吧？
![Screen Shot 2021-09-13 at 10 38 48 AM](https://user-images.githubusercontent.com/37086776/133015798-5a4c7014-641d-4223-b453-42cf0fed62de.png)

**Comment by Anonymous341** [comment]
> > EDID主要是显示器的色彩和控制，亮度控制是由显卡来驱动显示器的，edid没问题了亮度问题是显卡驱动和主板bios的ACPI规范适配引起的。oc版本有可能有关系，不过可能性很小。
> 
> ssdt亮度补丁的逻辑就是修改了acpi规范以适配显示驱动

哪我们主板和U 都是一样的4810MQ 和 LA-9772P， 没理由驱动会不同吧。就是一个EDID得改。 虽然驱动是打上了， 但是就是没有亮度调节。 太奇怪了。

**Comment by Anonymous341** [comment]
![Screen Shot 2021-09-13 at 11 43 08 AM](https://user-images.githubusercontent.com/37086776/133020771-dec048ad-4f88-4b17-8dba-0b9d1ce78564.png)
AppleBacklightDisplay 出来， 大致上就应该可以调了吧？

**Comment by hansyao** [comment]
> 这样算是兼容吗？ 还是还得改 ig-platform-id？我看 line 937-985 也不需动了吧？
> ![Screen Shot 2021-09-13 at 10 38 48 AM](https://user-images.githubusercontent.com/37086776/133015798-5a4c7014-641d-4223-b453-42cf0fed62de.png)

这个看不出来的，需要看3d加速和渲染是否完美

**Comment by hansyao** [comment]
另外你再检查下PNLF重命名有没有问题，见 [line 81-83](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L81-L83)的注释说明，这个是配合亮度补丁和bios适配的，最好看看重命名规范和你自己的BIOS是否匹配。
