### ISSUE TITLE
Display turned off during installation

### ISSUE THREAD

**Issue by samtech09** [badfellow/Hackintosh_M4800#5]
Hi, i trying with your EFI, but my display get turned off during installation at the screen with Apple Logo and progress bar. It get turned off after progress bar reaches approx 30%. And after some time, system goes to sleep mode as i could not make any action due to no display.

My M4800 config is almost same as with you except that, it has only NIVIDA Quadro K1100M VGA with QHD+ display. There is no Intel HD Graphics.

Here is my config
```
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I217-LM (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d4)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d4)
00:1c.3 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 (rev d4)
00:1c.4 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #5 (rev d4)
00:1c.6 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #7 (rev d4)
00:1c.7 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #8 (rev d4)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation QM87 Express LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107GLM [Quadro K1100M] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK107 HDMI Audio Controller (rev a1)
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 73)
```

I also added 'nvda_drv' to config.plist as mentioned in https://elitemacx86.com/threads/how-to-enable-nvidia-graphics-on-macos-clover-opencore.104/ , but it doesn't make any change.

Do you have any idea to fix that or point me in correct direction to overcome it ?

**Comment by hansyao** [comment]
Based upon your hardware list, you need to fix EDID injection [line 914-985](../blob/master/OpenCore/SSDT-Dell-M4800.dsl#L914-L985) , see issue [4#issuecomment-917599933](../issues/4#issuecomment-917599933).
in the meanwhile, you must fix the Intel Wireless Driver. see issue [2#issuecomment-877923827](../issues/2#issuecomment-877923827)

**Comment by hansyao** [comment]
Also pay attention to you BIOS settings to make sue Nvidia Optimus enabled. 'nvda_drv'  options you mentioned does not help as all features I had already fixed in SSDT injection according to ACPI specs.

**Comment by samtech09** [comment]
Thanks for pointing that out.

I replaced WiFi driver and also updated EDID that i extracted by running live linux OS. and replaced that in lines 938-948. But do not have any clue about following

```
"device-id", Buffer() { 0x12, 0x04, 0x00, 0x00 },
"pci-aspm-default",0x03,
"AAPL,ig-platform-id", Buffer() { 0x06, 0x00, 0x26, 0x0a },
"framebuffer-patch-enable", Buffer() { 0x01, 0x00, 0x00, 0x00 },
"framebuffer-cursormem", Buffer() { 0x00, 0x00, 0x90, 0x00 },
"framebuffer-unifiedmem", Buffer() { 0x00, 0x00, 0x00, 0x80 },
"framebuffer-fbmem", Buffer() { 0x00, 0x00, 0x90, 0x00 },
"hda-gfx", Buffer() { "onboard-1" },
```

What values should i put there for 'NVIDIA Quadro K1100M'. Is there any method to get those values ?

**Comment by hansyao** [comment]
> Thanks for pointing that out.
> 
> I replaced WiFi driver and also updated EDID that i extracted by running live linux OS. and replaced that in lines 938-948. But do not have any clue about following
> 
> ```
> "device-id", Buffer() { 0x12, 0x04, 0x00, 0x00 },
> "pci-aspm-default",0x03,
> "AAPL,ig-platform-id", Buffer() { 0x06, 0x00, 0x26, 0x0a },
> "framebuffer-patch-enable", Buffer() { 0x01, 0x00, 0x00, 0x00 },
> "framebuffer-cursormem", Buffer() { 0x00, 0x00, 0x90, 0x00 },
> "framebuffer-unifiedmem", Buffer() { 0x00, 0x00, 0x00, 0x80 },
> "framebuffer-fbmem", Buffer() { 0x00, 0x00, 0x90, 0x00 },
> "hda-gfx", Buffer() { "onboard-1" },
> ```
> 
> What values should i put there for 'NVIDIA Quadro K1100M'. Is there any method to get those values ?

You need to update EDID with modified H. Sync Width, in the meanwhile, increase framebuffer as your screen is QHD. you can follow the [guidance](https://dortania.github.io/OpenCore-Install-Guide) to see what's the suitable configuration for yours. 

one more thing, not sure you mainboard is same as mine as I can not see your device ID.  First of all, you need to check whether your mainboard model is la-9772p which exactly same as mine. If not, you could give it up to use my EFI.

**Comment by draskostar** [comment]
I bealive it will not work with internal screen because it is edp screen instead of lvds. try with external monitor through hdmi or dp

**Comment by samtech09** [comment]
Yes, it did not. I give up with that, instead i setup Linux there and using KVM to run Big Sur.
Performance is not high but enough to run Xcode.
