### ISSUE TITLE
Wakeup from sleep

### ISSUE THREAD

**Issue by draskostar** [badfellow/Hackintosh_M4800#6]
First of all thank you for very good EFI file. For me everything works except wake up from sleep. When AC power cord is pluged in wake up from sleep works. When I unplug my chrger and laptop is powerd only by battery then wake up from sleep does not work - when I press turn on button only black screek with backlight appears.

**Comment by hansyao** [comment]
You may try <kbd>Fn</kbd>+<kbd>F1</kbd> to see whether it works.

**Comment by draskostar** [comment]
Fn+F1 brings pc to sleep. It will not wake up with this command. To wake pc back alive the only way is by pressing a power button (which is blinking) but screen ends with black screen. For me it is strange that if pc is conected to AC then screen will wake up OK otherwise not.

**Comment by hansyao** [comment]
Can you post the verbose logging to see what stuck the wake?
